### ISSUE TITLE
Clicking Anime Skip logo in player breaks it

### ISSUE THREAD

**Issue by logiczsniper** [anime-skip/web-extension#210]
### Error in player
![image](https://user-images.githubusercontent.com/31292294/147874175-d78c10dd-b980-4bb1-a046-f24b00c84786.png)

### Error in console
![image](https://user-images.githubusercontent.com/31292294/147874281-ef22426c-807a-4310-9dda-bd220157fd5d.png)

### Resolution
My assumption is that the expected behavior is to open [anime-skip.com](https://www.anime-skip.com/) in a new tab - is this true?

**Comment by logiczsniper** [comment]
Simple fixes: 
1. add attribute `target="_blank"` to the `a` tag -> opens in a new tab instead of `iframe`
2. add attribute `target="_parent"` to the `a` tag -> opens in the parent window instead of `iframe`

**Comment by logiczsniper** [comment]
I'd be happy to open a PR once I know your thoughts @aklinker1 !

**Comment by aklinker1** [comment]
Yup, run it. I'll publish a release afterwards
